server:
  port: 8862
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
spring:
  application:
    name: service-miya
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8861/eureka/